apiVersion: v1
kind: Service
metadata:
  name: barista-service
  labels:
    app: barista
  # namespace: coffeeshop-prod
spec:
  clusterIP: None # Makes it a headless service
  selector:
    app: barista
