apiVersion: v1
kind: Service
metadata:
  name: kitchen-service
  labels:
    app: kitchen
  # namespace: coffeeshop-prod
spec:
  clusterIP: None # Makes it a headless service
  selector:
    app: kitchen
