apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  # You can add a namespace here if you plan to use one, e.g., namespace: coffeeshop-prod
type: Opaque
data:
  # Values must be base64 encoded.
  # echo -n 'rabbituser' | base64  => cmFiYml0dXNlcg==
  # echo -n 'rabbitpassword' | base64 => cmFiYml0cGFzc3dvcmQ=
  RABBITMQ_DEFAULT_USER: cmFiYml0dXNlcg==
  RABBITMQ_DEFAULT_PASS: cmFiYml0cGFzc3dvcmQ=
