apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service # This will be the DNS name pods use to connect
  labels:
    app: rabbitmq
  # You can add a namespace here if you plan to use one, e.g., namespace: coffeeshop-prod
spec:
  type: ClusterIP # Default, only reachable within the cluster
  ports:
    - name: amqp
      port: 5672 # Port the service listens on
      targetPort: 5672 # Port on the RabbitMQ pods (amqp port)
    - name: http-mgmt
      port: 15672 # Port the service listens on for management UI
      targetPort: 15672 # Port on the RabbitMQ pods (http-mgmt port)
  selector:
    app: rabbitmq # Selects pods with the label "app: rabbitmq" (from our Deployment)
