apiVersion: v1
kind: Secret
metadata:
  name: rds-db-credentials
  # namespace: coffeeshop-prod # if using a namespace, ensure it's consistent
type: Opaque
data:
  # Values must be base64 encoded.
  # DB_USER: echo -n 'coffeeshopadmin' | base64  => Y29mZmVlc2hvcGFkbWlu
  # DB_NAME: echo -n 'coffeeshop_prod_db' | base64 => Y29mZmVlc2hvcF9wcm9kX2Ri
  # DB_HOST: This will be the RDS endpoint, usually passed as a separate env var to apps.
  # DB_PORT: Usually 5432 for PostgreSQL, passed as a separate env var.

  DB_USER: Y29mZmVlc2hvcGFkbWlu
  DB_PASS: ZlBwTUljSlJkITFyeUk2VA== # Corrected base64 for fPpMIcJRd!1ryI6T
  DB_NAME: Y29mZmVlc2hvcF9wcm9kX2Ri
